# permissions for end users to view sudorequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sudorequest-viewer-role
rules:
- apiGroups:
  - k8sudo.jetstack.io
  resources:
  - sudorequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8sudo.jetstack.io
  resources:
  - sudorequests/status
  verbs:
  - get
