apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: sudoer
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["clusterroles"]
  verbs: ["sudo"]
