apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregate-sudorequests-admin-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["sudorequests.k8sudo.jetstack.io"]
  resources: ["sudorequests"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
rulesk:
- apiGroups: ["rbac.authorization.k8s.io"]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["clusterroles"]
  verbs: ["sudo"]
